Skillbox/dpo_python_django/04_DatabasesAndModels/board/advertisements_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ClassBasedView.as_view(), name='bill'),
]

Skillbox/dpo_python_django/04_DatabasesAndModels/board/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advertisements_app.urls'))
]

Skillbox/dpo_python_django/04_DatabasesAndModels/board/advertisements_app/models.py
from django.db import models


class Bill(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    price = models.FloatField(verbose_name='price', default=0)
    views_count = models.IntegerField(verbose_name='views count', default=0)
    author = models.ForeignKey('Person', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'bill'


class Person(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=254, default=None)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name

Skillbox/dpo_python_django/04_DatabasesAndModels/board/advertisements_app/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Bill


class ClassBasedView(ListView):
    template_name = "bill.html"
    model = Bill

Skillbox/dpo_python_django/04_DatabasesAndModels/board/advertisements_app/templates/bill.html
{% block content %}
  <h1>Bill List</h1>
  {% if bill_list %}
  <ul>
    {% for bill in bill_list %}
      <li>
        <a href="{{ bill.get_absolute_url }}">{{ bill.title }}</a>
        ({{bill.author}})
        ({{bill.price}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no bill in the library.</p>
  {% endif %}
{% endblock %}